name: ninjastudy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  speech_to_text: ^6.0.0
  avatar_glow: ^2.0.2
  firebase_core: ^1.24.0
  firebase_database: ^9.1.6
  firebase_auth: ^3.11.1
  cloud_firestore: ^3.5.0
  google_sign_in: ^5.4.2
  chat_bubbles: ^1.3.1
  connectivity_plus: ^2.3.9
  cached_network_image: ^3.2.2
  
  
dev_dependencies: 

  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.3

flutter: 
  uses-material-design: true

